# Generated by Django 6.0 on 2025-12-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='root_category',
            new_name='root',
        ),
    ]
