# Generated by Django 6.0 on 2026-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_platform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/imgs'),
        ),
    ]
