# Generated by Django 6.0 on 2026-01-22 16:58
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(
                to='users.profile',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sales',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=0
            ),
        ),
    ]
