# Generated by Django 6.0 on 2026-01-29 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderattributevalue'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_attributes', to='products.producttype')),
            ],
        ),
        migrations.AlterField(
            model_name='orderattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderattribute'),
        ),
    ]
