# Generated by Django 6.0 on 2026-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('sold', 'Продан'), ('hidden', 'Скрыт')], default='active', max_length=50),
        ),
    ]
