# Generated by Django 6.0 on 2026-01-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_values', to='products.product'),
        ),
    ]
