# Generated by Django 6.0 on 2026-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productattributevalue_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.TextField(max_length=255),
        ),
    ]
